### PR TITLE
Strips spaces from operation names before camelizing

### PR DESCRIPTION
**Pull request by feynmanliang**
We are running into this in https://github.com/fmops/oapi_hf/blob/main/mix.exs#L28

Operation tags with spaces currently get rendered as a pretty nasty name. For example, `tag = "Foo Bar"` results in `underscored_tag = "foo _bar"` and ultimately the collected operations module to be output to a file `lib/basemodulename/foo _bar.ex` with contends

```elixir
defmodule :"Elixir.BaseModuleName.Foo Bar" do
...
```

By removing spaces, this PR ensures the `underscored_tag` is `foo_bar` and results in the outputted module to be named `foo_bar.ex` (no spaces) with module name `BaseModuleName.FooBar` (no quoted atom).

### CODE REVIEW

**Comment by feynmanliang** [comment]
Yeah absolutely, can you point me to where dash replacement is happening?

**Comment by aj-foster** [comment]
Hi @feynmanliang, realizing that I messed up the tests related to naming when I renamed a module a while ago, I just pushed two commits to fix the tests and make the changes we discussed. When you have a chance, could you check and see if it still works for you?

**Comment by feynmanliang** [comment]
Thanks for the help! Unfortunately, it seems like 681815b is producing double underscores in the filename and combining camel and snake case in the module name. For repro:

I ran `mix deps.unlock` and `mix deps.get` to bump the `oapi_generator` dep to 681815b: https://github.com/fmops/text_generation_inference.ex/blob/test-oapi-patch/mix.lock#LL21C83-L21C123

I ran `mix api.gen default vendor/text-generation-inference/docs/openapi.json` which produced https://github.com/fmops/text_generation_inference.ex/blob/test-oapi-patch/lib/text_generation_inference/text__generation__inference.ex containing the aforementioned defects.

**Comment by aj-foster** [comment]
Thanks @feynmanliang for the reproduction! I now see that the issue was caused by not handling capitalized tags correctly. Commit cbaf0ce should fix this.

If it's okay with you, I will keep a copy of your spec as a test fixture in the future (full integration tests are on my to-do list).

**Comment by feynmanliang** [comment]
You are welcome to use the spec as a test case (it's huggingface's not mine)! Will give the update a run later today and report back.

**Pull request merged**
